feat/add_gui_for_SDFq
Crypto-TII/cryptographic_estimators pull request #37
Opened 2023-03-20 15:28 UTC by FloydZ

2023-03-22 06:37 UTC, Javierverbel submitted a review, later dismissed

2023-03-24 06:39 UTC, Memphisd requested changes
restructure parmeters

2023-03-24 06:39 UTC, Memphisd commented on input_dictionary.json
> +          "id": "memory_bound",
we said this s a problem parameter or not?

2023-03-24 06:39 UTC, Memphisd commented on input_dictionary.json
> +          "id": "nsolutions",
Same here, this is a problem parameter

2023-03-27 09:35 UTC, Memphisd requested changes

2023-03-27 09:35 UTC, Memphisd commented on input_dictionary.json
> +
here should be the is_syndrome_zero parameter, named "Code word search" as a selector

2023-03-27 09:35 UTC, Memphisd commented on input_dictionary.json
> +          "id": "memory_bound",
is a problem parameter

2023-03-27 09:35 UTC, Memphisd commented on input_dictionary.json
> +          "id": "nsolutions",
is a problem parameter

2023-03-27 10:06 UTC, Memphisd approved these changes

2023-03-27 11:33 UTC, merged